# Generated by Django 3.2.7 on 2023-08-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('has_water_level_pressure_sensor', models.BooleanField(default=False)),
                ('has_watering_pump', models.BooleanField(default=False)),
                ('sensor_val_to_inches_water_multiplier', models.FloatField()),
                ('sensor_reading_at_zero', models.FloatField(default=0.0)),
                ('num_barrels', models.IntegerField()),
                ('barrel_cross_sectional_area_in2', models.FloatField()),
                ('minimum_water_interval_hours', models.IntegerField()),
                ('watering_length_minutes', models.IntegerField()),
                ('watering_wait_minutes', models.IntegerField()),
                ('watering_repetitions', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('ipv4_address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IOTDeviceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.CharField(choices=[('sprinkle', 'Sprinkle'), ('get_status', 'Get Device Status')], default='get_status', max_length=100)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('interval_minutes', models.IntegerField()),
                ('next_execution', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sprinkler.iotdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_amount_inches', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SprinklerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('water_qty_at_start_gallons', models.FloatField()),
                ('water_level_at_end_gallons', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.iotdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IOTDeviceScheduleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.CharField(choices=[('sprinkle', 'Sprinkle'), ('get_status', 'Get Device Status')], default='get_status', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('exit_code', models.IntegerField()),
                ('iot_device_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.iotdeviceschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('supply_voltage', models.FloatField()),
                ('water_level_inches', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.iotdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
