# Generated by Django 3.2.7 on 2023-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatuslog',
            name='water_level_inches',
        ),
        migrations.AddField(
            model_name='devicestatuslog',
            name='supply_voltage_ticks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicestatuslog',
            name='water_pressure_psi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_high_ticks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_high_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_low_ticks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_low_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='devicestatuslog',
            name='supply_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='barrel_cross_sectional_area_in2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='num_barrels',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='sensor_val_to_inches_water_multiplier',
            field=models.FloatField(null=True),
        ),
    ]
