# Generated by Django 3.2.7 on 2023-09-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0002_auto_20230822_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='time_awake_start_hour_utc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='time_awake_stop_hour_utc',
            field=models.IntegerField(null=True),
        ),
    ]
