# Generated by Django 3.2.7 on 2023-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0003_auto_20230918_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainlog',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rainlog',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rainlog',
            name='total_amount_inches',
            field=models.FloatField(null=True),
        ),
    ]
