# Generated by Django 3.2.7 on 2023-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0004_auto_20230921_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdevice',
            old_name='cal_high_ticks',
            new_name='cal_high_ticks_voltage',
        ),
        migrations.RenameField(
            model_name='iotdevice',
            old_name='cal_low_ticks',
            new_name='cal_low_ticks_voltage',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='sensor_reading_at_zero',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='sensor_val_to_inches_water_multiplier',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_high_pressure_psi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_low_pressure_psi',
            field=models.FloatField(null=True),
        ),
    ]
