# Generated by Django 3.2.7 on 2024-09-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0005_auto_20231001_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='stay_awake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iotdeviceschedule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.iotdevice'),
        ),
    ]
