# Generated by Django 3.2.7 on 2024-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0006_auto_20240907_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatuslog',
            name='water_pressure_psi',
        ),
        migrations.AddField(
            model_name='devicestatuslog',
            name='water_pressure_ticks',
            field=models.IntegerField(null=True),
        ),
    ]
