# Generated by Django 3.2.7 on 2024-09-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0007_auto_20240907_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='cal_high_pressure_psi',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='cal_low_pressure_psi',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='time_awake_start_hour_utc',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='time_awake_stop_hour_utc',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_high_pressure_ticks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='cal_low_pressure_ticks',
            field=models.IntegerField(null=True),
        ),
    ]
