# Generated by Django 3.2.7 on 2024-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0008_auto_20240908_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdeviceschedule',
            name='schedule_type',
            field=models.CharField(choices=[('sprinkle', 'Sprinkle')], default='sprinkle', max_length=100),
        ),
        migrations.AlterField(
            model_name='iotdevicescheduleexecution',
            name='schedule_type',
            field=models.CharField(choices=[('sprinkle', 'Sprinkle')], default='sprinkle', max_length=100),
        ),
    ]
