# Generated by Django 3.2.7 on 2024-09-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0009_auto_20240908_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='ipv4_address',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='port',
        ),
    ]
