# Generated by Django 3.2.7 on 2024-09-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0010_auto_20240926_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdeviceschedule',
            name='interval_minutes',
        ),
    ]
