# Generated by Django 3.2.7 on 2024-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0011_remove_iotdeviceschedule_interval_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='minimum_water_interval_hours',
        ),
        migrations.AddField(
            model_name='iotdeviceschedule',
            name='minimum_interval_hours',
            field=models.IntegerField(default=168),
        ),
    ]
