# Generated by Django 3.2.7 on 2024-09-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0012_auto_20240926_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdeviceschedule',
            old_name='minimum_interval_hours',
            new_name='minimum_hours_between_executions',
        ),
    ]
