# Generated by Django 3.2.7 on 2025-05-01 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0013_rename_minimum_interval_hours_iotdeviceschedule_minimum_hours_between_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerToDeviceCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(choices=[('status', 'Status'), ('sprinkle_start', 'Sprinkle Start'), ('sprinkle_on', 'Sprinkle On'), ('sprinkle_off', 'Sprinkle Off'), ('sleep_now', 'Sleep'), ('switch_broker_debug', 'Switch Broker Debug'), ('switch_broker_prod', 'Switch Broker Prod'), ('power_off', 'Power Off')], max_length=100)),
                ('body', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.iotdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
