# Generated by Django 3.2.7 on 2025-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0014_servertodevicecommandlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='barrel_cross_sectional_area_in2',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='has_water_level_pressure_sensor',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='has_watering_pump',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='num_barrels',
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='cal_high_pressure_ticks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='cal_low_pressure_ticks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
